services:
  llama.cpp1:
    image: ghcr.io/ggml-org/llama.cpp:full-cuda
    container_name: llama.cpp1
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/llama.cpp:/root/.cache/llama.cpp
    command:
      - --server
      - --hf-repo
      - "ggml-org/gpt-oss-20b-GGUF"
      - --alias
      - "model1"
      - --port
      - "8000"
      - --host
      - "0.0.0.0"
      - --log-timestamps
      - --device
      - "CUDA1"
      - --no-webui
      - --api-key
      - "365016d2-ee13-4634-ba92-72ca23dc9813"
      - --ctx-size
      - "32768"
      - --jinja
      - -ub
      - "4096"
      - -b
      - "4096"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    networks:
      - caddy-net

  llama.cpp0:
    image: ghcr.io/ggml-org/llama.cpp:full-cuda
    container_name: llama.cpp0
    ports:
      - "8002:8002"
    volumes:
      - ~/.cache/llama.cpp:/root/.cache/llama.cpp
    command:
      - --server
      - --hf-repo
      - "ggml-org/gemma-3-4b-it-GGUF"
      - --alias
      - "model0"
      - --port
      - "8002"
      - --host
      - "0.0.0.0"
      - --log-timestamps
      - --device
      - "CUDA0"
      - --no-webui
      - --api-key
      - "365016d2-ee13-4634-ba92-72ca23dc9813"
      - --ctx-size
      - "8192"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    networks:
      - caddy-net

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    volumes:
      - ~/data/open-webui_data:/app/backend/data
    environment:
      #     - "QDRANT_API_KEY=API_KEY_HERE"
      #     - "QDRANT_URI=https://example.com"
      - ENABLE_ADMIN_CHAT_ACCESS=false
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "8001:8001"
      - "8003:8003"
    volumes:
      - ~/data/caddy_data/data:/data
      - ~/data/caddy_data/config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - caddy-net

networks:
  caddy-net:
    driver: bridge
