services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    environment:
      - TZ=America/Chicago
      - TUNNEL_TOKEN=${TOKEN}
    restart: unless-stopped
    command: tunnel --no-autoupdate run

  # clients
  portainer_agent:
    image: portainer/agent:lts
    container_name: portainer_agent
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    restart: unless-stopped

  # on server machine
  # portainer:
  #   image: portainer/portainer-ce:lts
  #   container_name: portainer
  #   # cloudflare tunnel to https://172.17.0.1:9443
  #   ports:
  #     - 9443:9443
  #   volumes:
  #     - ~/data/portainer_data:/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: "0 0 7 * * *"
      WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG: "servername"
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: fromaddress@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: toaddress@yahoo.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: fromaddress@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ${EMAIL_PASS}
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2

  # on clients
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/data/beszel_agent_data:/var/lib/beszel-agent
      # - ~/beszel_socket:/beszel_socket
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: ${BESZEL_KEY}
      TOKEN: ${BESZEL_TOKEN}
# on server machine
#  beszel:
#    image: henrygd/beszel:latest
#    container_name: beszel
#    restart: unless-stopped
#    ports:
#      - 8090:8090
#    volumes:
#      - ~/data/beszel_data:/beszel_data
#      - ~/data/beszel_socket:/beszel_socket

#  beszel-agent:
#    image: henrygd/beszel-agent-nvidia:latest
#    container_name: beszel-agent
#    restart: unless-stopped
#    network_mode: host
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ~/data/beszel_agent_data:/var/lib/beszel-agent
#      - ~/data/beszel_socket:/beszel_socket
#      # monitor other disks / partitions by mounting a folder in /extra-filesystems
#      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
#    environment:
#      LISTEN: /beszel_socket/beszel.socket
#      KEY: ${BESZEL_KEY}
#      TOKEN: ${BESZEL_TOKEN}
#      HUB_URL: http://localhost:8090
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities:
#                - utility

#  whoami:
#    image: traefik/whoami:v1.11
#    container_name: whoami
#    ports:
#      - 2001:2001
#    restart: unless-stopped
#    command:
#      - --port=2001
#      - --name=iamfoo

