services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    environment:
      - TZ=America/Chicago
      - TUNNEL_TOKEN=${TOKEN}
    restart: unless-stopped
    command: tunnel --no-autoupdate run

  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    # cloudflare tunnel to https://172.17.0.1:9443
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

#  whoami:
#    image: traefik/whoami:v1.11
#    container_name: whoami
#    ports:
#      - 2001:2001
#    restart: unless-stopped
#    command:
#      - --port=2001
#      - --name=iamfoo

volumes:
  data:
